### ISSUE TITLE
Boost Review Wizards report

### ISSUE THREAD

**Issue by robertramey** [iboB/boost.mixin#6]
Boost - Dev - Review Wizard Status Report for January 2015 | Threaded View

According to the Boost Review Wizards report, you have a library in the review queue.  Please consider raising the visibility of your library and encouraging people to experiment with while waiting for it to be reviewed.  You can do this by filling out a form on the www.blincubator.com - the boost library incubator.

Robert Ramey
Robert Ramey Software Development
(805)569-3793
ramey@rrsd.com
www.rrsd.com

**Comment by iboB** [comment]
It's already there: http://rrsd.com/blincubator.com/bi_library/boost-mixin/?gform_post_id=1122

**Comment by robertramey** [comment]
LOL - sorry - I missed that.

Robert Ramey
Robert Ramey Software Development
(805)569-3793
ramey@rrsd.com
www.rrsd.com
